iii-org/devops-ui

src/layout/components/Navbar.vue, src/permission.js, src/store/getters.js, src/store/modules/permission.js, src/store/modules/user.js, src/utils/auth.js
`fix`
- fix refresh page will logout error
`feat`
- navbar show user name
=> fix refresh page bug

src/api/cicd.js, src/router/index.js, src/views/CicdPipelines/index.vue, src/views/IssueDetail/index.vue, src/views/ProjectList/index.vue
`feat`
- use api get cicd pipeline and entrance from project name
=> cicd pipeline api

package.json, src/components/Wangeditor/index.vue, src/router/index.js, src/views/ProjectDocument/components/AddDocument.vue, src/views/ProjectDocument/index.vue, src/views/ProjectTopic/components/AddDocument.vue, src/views/ProjectTopic/index.vue, src/views/ProjectWiki/index.vue
`feat`
- add project doc list page
=> add project doc list page

src/router/index.js, src/store/modules/user.js, src/views/ProjectTopic/components/AddTopic.vue, src/views/ProjectTopic/index.vue, src/views/ProjectTopicDetail/components/FlowDialog.vue, src/views/ProjectTopicDetail/components/ParamDialog.vue, src/views/ProjectTopicDetail/index.vue
`feat`
- add comment, flow and param dialog in project topic
=> feat: add comment, flow and param dialog in project topic

src/views/IssueSetUp/components/DemandDialog.vue, src/views/IssueSetUp/components/ParamDialog.vue, src/views/IssueSetUp/components/TestDialog.vue, src/views/IssueSetUp/components/TestItemDialog.vue, src/views/IssueSetUp/components/TestValueDialog.vue, src/views/IssueSetUp/index.vue, src/views/MyIssues/index.vue, src/views/UserManage/components/UserDialog.vue, src/views/UserManage/index.vue, src/views/UserValidation/components/ValidateDialog.vue, src/views/UserValidation/index.vue
=> feat: add IssueSetUp page

src/api/user.js, src/views/UserManage/components/UserDialog.vue, src/views/UserManage/index.vue
`feat`
- userList data get from api
- add userList pagination
`fix`
- eslint formatter
=> AM user manage

src/api/issue.js, src/api/issueFlow.js, src/api/issueParameter.js, src/api/issueTestCase.js, src/api/issueTestItem.js, src/api/issueTestValue.js, src/api/projects.js, src/components/Wangeditor/index.vue, src/views/IssueSetUp/components/FlowDialog.vue, src/views/IssueSetUp/components/ParamDialog.vue, src/views/IssueSetUp/components/TestDialog.vue, src/views/IssueSetUp/components/TestItemDialog.vue, src/views/IssueSetUp/components/TestValueDialog.vue, src/views/IssueSetUp/index.vue, src/views/MyIssues/index.vue
`feat`
- add issue comment, flow, param, test case, test value crud
=> issue comment, flow, param, test case, test value crud

src/views/IssueSetUp/components/FlowDialog.vue, src/views/IssueSetUp/components/ParamDialog.vue, src/views/IssueSetUp/components/TestDialog.vue, src/views/IssueSetUp/components/TestItemDialog.vue, src/views/IssueSetUp/components/TestValueDialog.vue, src/views/IssueSetUp/index.vue
`feat`
- add form validation and check flow data is exist
=> add form validation and check flow data is exist

src/api/cicd.js, src/views/ProjectDevOps/index.vue, src/views/login/index.vue
`feat`
- add get pipelines phase page
=> feat: add get pipelines phase page

src/views/ProjectActivityLog/index.vue, src/views/ProjectCurrentActivity/index.vue, src/views/ProjectVersions/index.vue, src/views/UserManage/index.vue, src/views/dashboard/index.vue
`feat`
- ProjectCurrentActivity and ProjectActivityLog add loading
- UserManage and Dashboard remove useless feature
- ProjectVersion add form validation
=> feat: enhance and remove useless feature

src/router/index.js, src/views/Profile/index.vue
=> fix update user bug

src/views/MyIssues/index.vue, src/views/ProjectIssueDetail/index.vue, src/views/ProjectIssues/index.vue, src/views/ProjectVersions/index.vue
`fix`
- add rd my_issue last_test_result exist check
- issue assignee select show role error
- adjust project issue table column width
=> fix issue bug

src/api/projects.js, src/views/ProjectIssueDetail/index.vue, src/views/UserManage/components/UserDialog.vue
`fix`
- user enable field change to statue (enable/disable)
- issue update support assigned user and version
- get project assignable user change parameter
=> fix pm ui bug

src/views/UserManage/components/UserDialog.vue
Don't close this PR and merge it each time you want to.
=> Continously PR from personal develop branch

src/styles/custom.scss, src/views/OverviewProject/components/project_bar.vue, src/views/OverviewProject/components/project_pie.vue, src/views/ProcessDevBranch/index.vue, src/views/ProgressDevVersionTestRecord/components/TestDetail.vue, src/views/ProgressDevVersionTestRecord/index.vue, src/views/ProjectListPM/index.vue, src/views/ProjectWiki/index.vue
/progress/dev-branch
/progress/test-record and detail
/list (project list progress width)
=> Progress table

src/styles/custom.scss, src/views/ProjectIssueDetail/components/FlowDialog.vue, src/views/ProjectIssueDetail/components/ParamDialog.vue, src/views/ProjectIssueDetail/index.vue, src/views/ProjectIssues/components/AddIssue.vue
=> Issue add and edit

src/styles/custom.scss, src/views/ProjectDevOps/index.vue, src/views/ProjectMembers/index.vue, src/views/ProjectVersions/index.vue
=> Setting style

src/components/Kanban/index.vue, src/styles/custom.scss, src/views/ProjectCurrentActivity/index.vue
=> current activity style

src/styles/custom.scss, src/views/ProjectActivityLog/index.vue
=> FIX: Activity log style

public/imgs/link-icon.svg, src/lang/zh.js, src/styles/custom.scss, src/styles/variables.scss, src/views/IssueDetail/components/EditIssue.vue, src/views/ProjectIssueDetail/index.vue, src/views/ProjectIssues/components/AddIssue.vue, src/views/ProjectIssues/index.vue, src/views/ProjectListPM/index.vue, src/views/ProjectMembers/index.vue
更新畫面：
- 成員設定的欄寬
- 專案列表的 name/identifier 切開
- 議題列表樣式
- 新增 subissue(需自行串 API)
- 新增 subissue 附件拖曳上傳(需自行串 API)
=> Issue list

src/views/ProjectIssues/index.vue, src/views/ProjectListPM/index.vue
解決 Project Issue List 在小螢幕時文字重疊問題(固定最小欄寬)
=> Project Issue List 文字重疊問題
